services:
  betting-interface:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
    env_file:
      - .env
    stdin_open: true
    tty: true